[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "market-analyzer"
version = "0.1.0"
dependencies = [
    "pandas",
    "numpy",
    "altair"
]

[tool.setuptools.packages.find]
where = ["src"]